### ISSUE TITLE
Add Carthage support

### ISSUE THREAD

**Issue by kean** [kean/Nuke-AnimatedImage-Plugin#1]
Waiting for https://github.com/Flipboard/FLAnimatedImage/pull/95

**Comment by toshi0383** [comment]
+1

seems like Flipboard/FLAnimatedImage#95 is closed ?

**Comment by kean** [comment]
I think that there won't be a need for Carthage soon https://swift.org/package-manager/

**Comment by toshi0383** [comment]
Man !

**Comment by kean** [comment]
done https://github.com/kean/Nuke-AnimatedImage-Plugin/releases/tag/0.4.0
