### ISSUE TITLE
Preheating gifs with Nuke

### ISSUE THREAD

**Issue by juanmadurand** [kean/Nuke-AnimatedImage-Plugin#13]
Hello @kean,
first of all, thank you for your amazing work. I've been using this plugin for a deck of gif cards.

It's working great, but what I'm trying to do now is to prefetch the gifs, so I can be ahead of time with ~10 gifs and keep showing gifs even if you are offline.

The ideal scenario for me is:
1st card - playing gif
2nd and 3rd card - showing poster (gif prefetched)
4th~10th - gif prefetched

Is there a way I could achieve this using this plugin and the preheating feature from Nuke? (https://github.com/kean/Nuke#preheating-images)

Also, in order to show the poster, do I need an extra view? I only have an `AnimatedImageView` right now.

Thanks!

**Comment by kean** [comment]
Sorry, I somehow missed this question. I think I wasn't subscribed to a repo.
