### ISSUE TITLE
Error Populated when i am going to display Gif

### ISSUE THREAD

**Issue by SomNai** [kean/Nuke-AnimatedImage-Plugin#14]
![screen shot 2018-04-07 at 4 13 21 pm](https://user-images.githubusercontent.com/35223580/38454146-08479c2a-3a7f-11e8-9046-5aa3b43eed47.png)

**Comment by kean** [comment]
Sorry, I forgot to update the README with 4.0 changes. Just did it now.

**Comment by SomNai** [comment]
sorry, its my mistake i passed string instead of url
