### ISSUE TITLE
No type named '<some type>' in module 'Nuke'

### ISSUE THREAD

**Issue by TannerJuby1** [kean/Nuke-AnimatedImage-Plugin#15]
After running a `pod update` I am receiving a bunch of errors of the type `No type named '<some type>' in module 'Nuke'`.. It works perfectly fine before I attempted the update.

Here is what I have in my pod file for Nuke: 

```
    pod 'Nuke', '~> 7.3'
    pod 'Nuke-FLAnimatedImage-Plugin'
```

**Comment by kean** [comment]
Hi, @TannerJuby1! I haven't updated this pod in a while, let me see.

**Comment by kean** [comment]
Update the plugin to work with Nuke 7.5 - https://github.com/kean/Nuke-FLAnimatedImage-Plugin/releases/tag/6.0, should work well now 😉
