### ISSUE TITLE
Why should I combine Nuke and FlAnimateImage?

### ISSUE THREAD

**Issue by donxyen** [kean/Nuke-AnimatedImage-Plugin#16]
What's the purpose of combining these two libraries when I can each use them to display GIFs locally and over network?

**Comment by kean** [comment]
Nuke fetches and caches the data, FLAnimatedImage renders it.

**Comment by donxyen** [comment]
Right now, I have a CollectionView that has hundreds of GIFs loaded at viewDidLoad(). This creates a huge memory problem where the app starts to slow down and crash at about 900mb-1.2gb. I looked in Allocation and see that "VM: CG raster data" is responsible for this memory leak.

Can I use Nuke to cache local GIFs from the main bundle that is rendered by FLAnimatedImage? 

I'm thinking of a local caching solution to offload data when collectionView didEndDisplaying data and load back data with willDisplayCell.

**Comment by kean** [comment]
> I'm thinking of a local caching solution to offload data when collectionView didEndDisplaying data and load back data with willDisplayCell.

That's exactly what Nuke does for you. It can load data from disk on demand when cell is displayed. It puts the data in the memory cache which uses a limited percentage of memory. It works both with still and with animated images really well.

Check out the demo project the main Nuke repo to see how it works in practice.
