### ISSUE TITLE
Memory usage keeps growing

### ISSUE THREAD

**Issue by mitchellporter** [kean/Nuke-AnimatedImage-Plugin#4]
I just spent the entire day trying to figure this out and I still can't get it. Run the animated gif example project, and look at the Debug Navigator tab in the left side panel. If you pay attention to the memory usage, it starts out around anywhere from 10 - 15 MB. Now don't even scroll, just let the app sit there. If you wait 3-5 minutes and come back, the memory usage will now be at 40-50 MB. This will keep growing and growing if you let the app keep running. It literally never stops.

I ran this through instruments and it looks like the Anonymous VM is what keeps growing, which is too bad because this is the system's way of estimating how much memory the app will need in the future. I have been researching a lot today and can't seem to figure this out.

Any ideas Alexander?

**Comment by mitchellporter** [comment]
Bump. I just checked the app again after leaving it running all this time, memory is now at 158 MB

**Comment by kean** [comment]
Hi, 

Displaying animated GIFs is a memory-intesive task. A single small (in terms of original data) GIF might take tens or hundreds MBs in memory. I don't see a problem with using memory in itself, its inevitable. The FLAnimatedImage does its best by 1) **not** decoding all frames upfront like SDWebImage 2) clearing  buffers for decoded frames on memory warnings.

But, there is a problem with using a memory cache in Nuke though. I prefer just to disable it for GIFs. The problem is that the buffer for decoded frames is stored right into an instance of FLAnimatedImage object, which makes it hard to reuse those objects. Nuke doesn't handle that problem very well at the moment. If you enable memory cache it would store instances of the FLAnimatedImage objects with all the consequences. It's not critical, but it might bite you if display the same animated image in multiple places.

**Comment by kean** [comment]
And it is possible to do better then that. Nuke should:
1. Stop storing instances of FLAnimatedImage objects into a memory cache, store only original NSData instead (wrapped into an Nuke.AnimatedImage class)
2. Create a new instance of FLAnimatedImage each time it is displayed (can be handled in FLAnimatedImageView extension)
3. Add a specific memory cache implementation that would calculate cost of Nuke.AnimatedImage objects based on the size of NSData

Or, like I said, you should just disable memory cache for animated GIFs. I think that's the safest solution in terms of memory usage.

**Comment by mitchellporter** [comment]
Thanks for such quick feedback. Before we go down the road of making possible changes to Nuke, what's the fastest way for me to simply disable memory cache for animated gifs?

**Comment by kean** [comment]
Override either `func setResponse(response: ImageCachedResponse, forKey key: ImageRequestKey)` method of `ImageMemoryCache` class, or `public func setResponse(response: ImageCachedResponse, forRequest request: ImageRequest)` method of `ImageManager` class. Check if the image is an instance of `Nuke.AnimatedImage` class and return.

**Comment by kean** [comment]
> Before we go down the road of making possible changes to Nuke

I already had that in mind for a while, but it wasn't a priority. I might implement it now, it's a straightforward change.

**Comment by mitchellporter** [comment]
> I already had that in mind for a while, but it wasn't a priority. I might implement it now, it's a straightforward change.

Before you look into it, we might be wasting our time. This might just be an issue with FLAnimatedImage. I just modified both of those methods and they no longer have any functionality at all, yet the emory issue still persists.

**Comment by mitchellporter** [comment]
After temporarily removing Nuke from my project, I analyzed multiple gif libraries and it turns out most of them either have low memory and high CPU usage, or high memory and low CPU usage.

I ended up using the following gif library: https://github.com/kaishin/Gifu

It's written and Swift, and still does experience some mildly high memory usage when used in a collection view, but I was able to lower the memory usage using some tweaks.

I'm going to see if I can integrate this into Nuke to replace FLAnimatedImage, and then will test in Instruments to make sure that Nuke's caching does not have a negative hit on performance.

**Comment by mitchellporter** [comment]
Ok so I looked into integrating Gifu but the problem I'm having is that Nuke revolves around always returning images, but the Gifu library library that I linked to above requires NSData in the initializer. I've thought of ways to make this work like getting raw data from the image returned by Nuke, but that's doing double the work since Nuke already had the data to create the image.

I want to be able to take advantage of the request logic, preheating logic, etc. but I don't see how that'll be possible if I continue to use this Gifu library.

Any advice Alexander?

**Comment by kean** [comment]
You could do it the same way FLAnimatedImage is handled:

In `ImageDecoding` class:
1. Check if data is GIF
2. Create first image frame (`CGImageSourceCreateImageAtIndex(imageSource, 0, nil)`
3. Create an instance of some `AnimatedImage: UIImage` class with the first frame and with the original image data. Store original image data in a property.

Alternatively:
1. Check if data is GIF
2. Create an instance of `AnimatedImage: UIImage` just with the original image data. `UIImage` is going to be empty

Yet as another alternative:
1. Create an empty UIImage. Add original animated image data as an associated object.

**Comment by kean** [comment]
Gifu seems too basic btw, at least there is no support for variable frame delays. If you treat `FLAnimatedImage` class as an `Animator` class from Gifu, it would work just as well. I'm going to make that change today.

**Comment by kean** [comment]
@mitchellporter you might want to check out https://github.com/kean/Nuke-AnimatedImage-Plugin/issues/5. I'm releasing new version of plugin soon, it should resolve all memory issues. I would suggest sticking with FLAnimatedImage, it's better in multiple ways.

**Comment by mitchellporter** [comment]
@kean You are correct. At first I thought `Gifu` was a better solution because the CPU usage was lower but upon further inspection I realized that current scrolling performance is not nearly as good as `FLAnimatedImage`. I think the best choice is to stick with `FLAnimatedImage` which is what I plan on doing.

**Comment by kean** [comment]
So, I've actually released a new version https://github.com/kean/Nuke-AnimatedImage-Plugin/releases/tag/0.6.0 and I'm very happy with the way it works.

**Comment by mitchellporter** [comment]
@kean This looks awesome! Great work, and thank you!
