### ISSUE TITLE
Create FLAnimatedImage each time the Nuke.AnimatedImage is displayed

### ISSUE THREAD

**Issue by kean** [kean/Nuke-AnimatedImage-Plugin#5]
Nuke should:
1. Stop storing instances of FLAnimatedImage objects into a memory cache, store only original NSData instead (wrapped into an Nuke.AnimatedImage class)
2. Create a new instance of FLAnimatedImage each time it is displayed (can be handled in FLAnimatedImageView extension)

Based on https://github.com/kean/Nuke-AnimatedImage-Plugin/issues/4

**Comment by kean** [comment]
Here's a simple case that I'm optimizing for: 

> There are two cells in a horizontal collection view, each cell takes an entire screen's width. The user watches the entire first GIF and then scrolls to the right to watch the second one. As soon as the first image goes offscreen, the image view is cleared.
> [memory cache is enabled]

I would expect the memory usage to grow just a tiny bit. The persistent memory should only contain a frame buffer the first image, plus the original data (`NSData`) for the first image.

Here's the data from the profiler _before_:
1. Not displaying anything:
   ![screen shot 2016-02-11 at 17 40 08](https://cloud.githubusercontent.com/assets/1567433/12979219/c3ccf1b6-d0e6-11e5-91ed-3e282faddf53.png)
2. Displaying the first image:
   ![screen shot 2016-02-11 at 17 40 32](https://cloud.githubusercontent.com/assets/1567433/12979228/cb346376-d0e6-11e5-98a9-9f2dba92dd6b.png)
3. Displaying the second image:
   ![screen shot 2016-02-11 at 18 49 54](https://cloud.githubusercontent.com/assets/1567433/12981090/466cdefc-d0f0-11e5-86df-c15bf1fba497.png)

**Comment by kean** [comment]
Testing after the change:
1. Not displaying anything:
   ![screen shot 2016-02-11 at 18 52 13](https://cloud.githubusercontent.com/assets/1567433/12981196/b0927f6c-d0f0-11e5-9b23-5344b9ea12c9.png)
2. Displaying the first image:
   ![screen shot 2016-02-11 at 18 52 22](https://cloud.githubusercontent.com/assets/1567433/12981200/b9672bb0-d0f0-11e5-8406-84ac212f7b3c.png)
3. Displaying the second image:
   ![screen shot 2016-02-11 at 18 52 34](https://cloud.githubusercontent.com/assets/1567433/12981218/c6219516-d0f0-11e5-851a-c8a4f28d4b2c.png)

The memory usage drop dramatically.

The original version resulted in an extra 6.94 Mb of persistent memory being after the step 3.
The new version results in just 1.28 Mb (72% smaller) grows.

**Comment by kean** [comment]
The benefits of this change:
- huge reduction in memory usage
- it's now easier to compute cost in mem. cache
- prevents instance of FLAnimatedImage class from ever being reused in multiple views which could results in issues during rendering

**Comment by kean** [comment]
Closed by a6e6142a2cb1689bba7f76ebc918478edffe1c6c

**Comment by kean** [comment]
Should also disable predrawing to make it work smoothly.

**Comment by mitchellporter** [comment]
@kean do you plan on releasing this soon and updating the CocoaPod or should I just pull straight from the repo?

Excellent work by the way, really appreciate it.

**Comment by kean** [comment]
@mitchellporter well, it's not all that great as I initially thought. My idea was to store NSData into memory cache and create FLAnimatedImage each time the image is displayed. But unfortunately, creating FLAnimatedImage is a _really_ expensive operation, because of this part:

``` objective-c
// Iterate through frame images
        size_t imageCount = CGImageSourceGetCount(_imageSource);
        NSUInteger skippedFrameCount = 0;
        NSMutableDictionary *delayTimesForIndexesMutable = [NSMutableDictionary dictionaryWithCapacity:imageCount];
        for (size_t i = 0; i < imageCount; i++) {
            @autoreleasepool {
                CGImageRef frameImageRef = CGImageSourceCreateImageAtIndex(_imageSource, i, NULL);
```

Apparently they traverse all frames upfront to determine `delay time` for each frame. This is required to support variable frame delays. So you can't create instances of FLAnimatedImage class on the main thread.

I'm kinda stuck at the moment.

**Comment by mitchellporter** [comment]
@kean Not trying to sound negative, but I have a feeling the current solution is as good as it's going to get with `FLAnimatedImage`. Honestly, gifs, at least in collection views / table views and displaying many on screen at once, should not be rendered on the CPU but on the GPU. There's only so many optimizations that can be done.

That being said, any thoughts on my comment? https://github.com/Flipboard/FLAnimatedImage/issues/115#issuecomment-183042310

I feel like the current solution with `Nuke` + `FLAnimatedImage` is as good as it can get. You've already done a great job of optimizing all of this from the beginning.
