### ISSUE TITLE
Migrate to Swift 3

### ISSUE THREAD

**Issue by MatthewYe** [kean/Nuke-AnimatedImage-Plugin#9]
Is there any plan about migrate this plugin to Swift 3.0?
@kean

**Comment by kean** [comment]
Hey @MatthewYe! Sure, there is a working Swift 3 + Nuke 4 compatible version in `swift3` branch. Here's how to install it using CocoaPods:

``` ruby
pod 'Nuke-AnimatedImage-Plugin', :git => 'https://github.com/kean/Nuke-AnimatedImage-Plugin', :branch => 'swift3'
```

I'm going to release updated plugins alongside Nuke 4.0, which I'm going to release soon (current version is Nuke 4.0-beta3).

**Comment by MatthewYe** [comment]
@kean Thank you very much.
I'm using Carthage to manage dependencies.
Is there anyway use Carthage to install branch Swift3 or should i use CocoaPod instead Carthage for both Nuke and plugin?

**Comment by kean** [comment]
Carthage is also supported:

```
// Cartfile
github "Nuke-AnimatedImage-Plugin" "swift3"
```

**Comment by MatthewYe** [comment]
//Cartfile
github "kean/Nuke-AnimatedImage-Plugin" "swift3"
this did work.
Thanks again.Great help to me ! Thank you
@kean

**Comment by MatthewYe** [comment]
hi @kean 
back to Swift 2

``` swift
let decoder = ImageDecoderComposition(decoders: [AnimatedImageDecoder(), ImageDecoder()])
let loader = ImageLoader(configuration: ImageLoaderConfiguration(dataLoader: <#dataLoader#>, decoder: decoder), delegate: AnimatedImageLoaderDelegate())
let cache = AnimatedImageMemoryCache()
ImageManager.shared = ImageManager(configuration: ImageManagerConfiguration(loader: loader, cache: cache))
```

plugin should do init as before.
is it right do the same thing like:

``` swift
let manager: Nuke.Manager = {
    let decoder = NukeAnimatedImagePlugin.DataDecoderComposition(decoders: [AnimatedImageDecoder(), Nuke.DataDecoder()])
    let cache = Nuke.Cache().preparedForAnimatedImages()
    let loader = Nuke.Loader(loader: Nuke.DataLoader(), decoder: decoder, cache: cache)
    return Manager(loader: loader, cache: cache)
}()
Manager.shared = manager
```

**Comment by kean** [comment]
@MatthewYe, yeah that should work.

In Nuke 4 you should also disable decompression for animated images:

``` swift
var request = Request(url: imageURLs[indexPath.row])

// as an alternative you can wrap existing processor in AnimatedImageProcessor
            request.processor = nil
```

P.S. I'm working on making AnimatedImage plugin setup simpler for the next version.

**Comment by MatthewYe** [comment]
@kean Thank you! 😄

**Comment by kean** [comment]
Ok, so the setup process is going to look like this in Nuke 4.0:

``` swift
Manager.shared = NukeAnimatedImagePlugin.makeDefaultManager()
```
- no manual wiring of dependencies (which you can still do if you need to)
- no `request.processor = nil` step when creating a `Request`.

I'm going to release Nuke 4.0 _soon_ with updated [Migration Guide](https://github.com/kean/Nuke/blob/master/Docs/Nuke%204%20Migration%20Guide.md) which will mention Nuke plugins.

**Comment by MatthewYe** [comment]
@kean looking forward the Nuke 4.0 been released!

`Manager.shared = NukeAnimatedImagePlugin.makeDefaultManager()`
is this has been released in NukeAnimatedImagePlugin
Actually ,i'm stocked in NukeAnimatedImagePlugin.
I get almost everything ticking in Swift 3.0. but i'm not sure,where i did wrong.

here is code i modified

``` Swift
class MediaView: UIView {
    static let sharedImageManager:Manager = {
        let decoder = NukeAnimatedImagePlugin.DataDecoderComposition(decoders: [AnimatedImageDecoder(), Nuke.DataDecoder()])
        let cache = Nuke.Cache().preparedForAnimatedImages()
        let loader = Nuke.Loader(loader: Nuke.DataLoader(), decoder: decoder, cache: cache)
        return Manager(loader: loader, cache: cache)
    }()
...
```

``` Swift
...
if viewModel.isGif {
            photoImageView = FLAnimatedImageView()
        } else {
            photoImageView = UIImageView()
        }
```

``` Swift
...
 var request = Request(url: viewModel.mediaUrl)
        if viewModel.isGif{
            request.processor = nil
            MediaView.sharedImageManager.loadImage(with: request, into: photoImageView)
        }else{
            Nuke.loadImage(with: request, into: photoImageView)
        }
```

There was only static cover instead Gif.

 Maybe only CocoaPod is easier to debug figured out what happened in Framework.

**Comment by kean** [comment]
There is yet another step required to make NukeAnimatedImagePlugin work. After loading an image you should manually call a special `nk_display` method on `FLAnimatedImage`. Otherwise Nuke doesn't know how to display an animated GIF.

Here's an example from Animated Image Demo:

``` swift
manager.loadImage(with: request, into: imageView) { response, isFromMemoryCache in
    switch response {
    case let .fulfilled(image):
        imageView.nk_display(image)
        if !isFromMemoryCache {
            let animation = CABasicAnimation(keyPath: "opacity")
            animation.duration = 0.25
            animation.fromValue = 0
            animation.toValue = 1
            let layer: CALayer? = imageView.layer // Make compiler happy on OSX
            layer?.add(animation, forKey: "imageTransition")
        }
    case .rejected(_): return
    }
}
```

I'm sorry this is such a convoluted and not-documented process at the moment. I hope to smooth everything out soon to a single method.

**Comment by kean** [comment]
btw, here's how to [insert code blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/) 🍻

**Comment by MatthewYe** [comment]
@kean yeah~ ! that's better now! thanks 😄

**Comment by MatthewYe** [comment]
Cool,FLAnimatedImageView is working with Nuke smooooooth ~ and fast now!

@kean 

Thank you!

**Comment by kean** [comment]
Thanks for your interest. Cheers 🍻
